modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
issueTrackerURL = "${project_issues}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${project_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"