# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defense
# against bad commits.

name: Build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17
        ]
        # and run both Linux and not Windows
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checkout repository
      - name: checkout repository
        uses: actions/checkout@v4

      # Validate gradle wrapper
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      # Setup JDK
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      # Make gradle wrapper executable if not on Windows
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Build the mod
      - name: build
        run: ./gradlew build

      # Check fabric artifacts
      - name: capture fabric's build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v4
        with:
          name: Fabric
          path: fabric/build/libs/
          if-no-files-found: error

      # Check common artifacts
      - name: capture the common build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v4
        with:
          name: Common
          path: common/build/libs/
          if-no-files-found: error

      # Check merged artifacts
      - name: capture the merged build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v4
        with:
          name: Merged
          path: build/libs/merged
          if-no-files-found: warn

      # Check forge artifacts
      - name: capture forge's build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v4
        with:
          name: Forge
          path: forge/build/libs/
          if-no-files-found: error

      # Check quilt artifacts
      - name: capture quilt's build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v4
        with:
          name: Quilt
          path: quilt/build/libs/
          if-no-files-found: error