name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: checkout repository
        uses: actions/checkout@v4

      # Validate gradle wrapper
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      # Setup JDK
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      # Make gradle wrapper executable if not on Windows
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      # Build the mod
      - name: build
        run: ./gradlew build

      # Publish forge mod
      - name: publish forge mod
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 3yiMtfYs
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1010303
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            forge/build/libs/*-forge.jar

      # Publish fabric mod
      - name: publish fabric mod
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 3yiMtfYs
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1010303
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            fabric/build/libs/*-fabric.jar